"""Realistic device presets for each import source."""

IMPORT_PRESETS: dict[str, dict] = {
    # =========================================================================
    # HOME ASSISTANT
    # =========================================================================
    "home_assistant": {
        "system_info": {
            "version": "2025.12.1",
            "name": "Home Assistant",
            "location": "Kyiv, Ukraine",
            "units": "metric",
            "device_count": 14,
            "automation_count": 8,
            "scene_count": 4,
        },
        "devices": [
            {
                "name": "Стельова лампа",
                "type": "light",
                "room": "Вітальня",
                "protocol": "ha_websocket",
                "manufacturer": "IKEA",
                "model": "LED1545G12",
                "source_entity_id": "light.living_room_ceiling",
                "protocol_config": {"friendly_name": "living_room_ceiling"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 370},
                "capabilities": ["brightness", "color_temp"],
            },
            {
                "name": "Торшер",
                "type": "light",
                "room": "Вітальня",
                "protocol": "ha_websocket",
                "manufacturer": "IKEA",
                "model": "LED1836G9",
                "source_entity_id": "light.living_room_floor_lamp",
                "protocol_config": {"friendly_name": "living_room_floor_lamp"},
                "state": {"state": "OFF", "brightness": 200, "color_temp": 300},
                "capabilities": ["brightness", "color_temp"],
            },
            {
                "name": "Лампа тумбочка",
                "type": "light",
                "room": "Спальня",
                "protocol": "ha_websocket",
                "manufacturer": "Aqara",
                "model": "ZNLDP12LM",
                "source_entity_id": "light.bedroom_nightstand",
                "protocol_config": {"friendly_name": "bedroom_nightstand"},
                "state": {"state": "OFF", "brightness": 180, "color_temp": 400},
                "capabilities": ["brightness", "color_temp"],
            },
            {
                "name": "Датчик руху",
                "type": "sensor",
                "room": "Коридор",
                "protocol": "ha_websocket",
                "manufacturer": "Aqara",
                "model": "RTCGQ11LM",
                "source_entity_id": "binary_sensor.hallway_motion",
                "protocol_config": {"friendly_name": "hallway_motion"},
                "state": {"occupancy": False, "battery": 87, "illuminance": 45},
                "capabilities": ["occupancy", "battery", "illuminance"],
            },
            {
                "name": "Датчик дверей вхідних",
                "type": "sensor",
                "room": "Коридор",
                "protocol": "ha_websocket",
                "manufacturer": "Aqara",
                "model": "MCCGQ11LM",
                "source_entity_id": "binary_sensor.front_door",
                "protocol_config": {"friendly_name": "front_door"},
                "state": {"contact": True, "battery": 92},
                "capabilities": ["contact", "battery"],
            },
            {
                "name": "Термостат",
                "type": "climate",
                "room": "Вітальня",
                "protocol": "ha_websocket",
                "manufacturer": "TuYa",
                "model": "TS0601_thermostat",
                "source_entity_id": "climate.living_room_thermostat",
                "protocol_config": {"friendly_name": "living_room_thermostat"},
                "state": {"current_temperature": 21.5, "target_temperature": 22.0, "hvac_mode": "heat", "fan_mode": "auto", "preset": "none", "humidity": 48},
                "capabilities": ["temperature", "humidity", "fan_mode", "preset"],
            },
            {
                "name": "Датчик температури",
                "type": "sensor",
                "room": "Спальня",
                "protocol": "ha_websocket",
                "manufacturer": "Aqara",
                "model": "WSDCGQ11LM",
                "source_entity_id": "sensor.bedroom_temperature",
                "protocol_config": {"friendly_name": "bedroom_temperature"},
                "state": {"temperature": 20.8, "humidity": 52, "battery": 78},
                "capabilities": ["temperature", "humidity", "battery"],
            },
            {
                "name": "Розумна розетка",
                "type": "switch",
                "room": "Кухня",
                "protocol": "ha_websocket",
                "manufacturer": "Xiaomi",
                "model": "ZNCZ02LM",
                "source_entity_id": "switch.kitchen_plug",
                "protocol_config": {"friendly_name": "kitchen_plug"},
                "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0},
                "capabilities": ["power_monitoring"],
            },
            {
                "name": "Телевізор Samsung",
                "type": "media_player",
                "room": "Вітальня",
                "protocol": "ha_websocket",
                "manufacturer": "Samsung",
                "model": "UE55AU7100",
                "source_entity_id": "media_player.samsung_tv",
                "protocol_config": {"friendly_name": "samsung_tv"},
                "state": {"state": "idle", "volume_level": 0.3, "is_volume_muted": False, "media_title": "", "media_artist": "", "media_content_type": "video", "source": "HDMI1"},
                "capabilities": ["volume", "media_control", "source"],
            },
            {
                "name": "Пилосос Roborock",
                "type": "vacuum",
                "room": "Вітальня",
                "protocol": "ha_websocket",
                "manufacturer": "Roborock",
                "model": "S7 MaxV",
                "source_entity_id": "vacuum.roborock_s7",
                "protocol_config": {"friendly_name": "roborock_s7"},
                "state": {"state": "docked", "battery": 100, "fan_speed": "standard", "cleaned_area": 0.0, "cleaning_time": 0},
                "capabilities": ["battery", "fan_speed"],
            },
            {
                "name": "Штори вітальня",
                "type": "cover",
                "room": "Вітальня",
                "protocol": "ha_websocket",
                "manufacturer": "Aqara",
                "model": "ZNCLDJ11LM",
                "source_entity_id": "cover.living_room_curtain",
                "protocol_config": {"friendly_name": "living_room_curtain"},
                "state": {"state": "closed", "position": 0, "tilt_position": 0},
                "capabilities": ["position", "tilt"],
            },
            {
                "name": "Замок вхідних дверей",
                "type": "lock",
                "room": "Коридор",
                "protocol": "ha_websocket",
                "manufacturer": "Nuki",
                "model": "Smart Lock 3.0 Pro",
                "source_entity_id": "lock.front_door_lock",
                "protocol_config": {"friendly_name": "front_door_lock"},
                "state": {"state": "locked", "battery": 85, "door_state": "closed"},
                "capabilities": ["battery"],
            },
            {
                "name": "Датчик протікання",
                "type": "sensor",
                "room": "Ванна",
                "protocol": "ha_websocket",
                "manufacturer": "Aqara",
                "model": "SJCGQ11LM",
                "source_entity_id": "binary_sensor.bathroom_water_leak",
                "protocol_config": {"friendly_name": "bathroom_water_leak"},
                "state": {"water_leak": False, "battery": 95},
                "capabilities": ["water_leak", "battery"],
            },
            {
                "name": "Лампа кухня",
                "type": "light",
                "room": "Кухня",
                "protocol": "ha_websocket",
                "manufacturer": "Yeelight",
                "model": "YLDP06YL",
                "source_entity_id": "light.kitchen_ceiling",
                "protocol_config": {"friendly_name": "kitchen_ceiling"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 250, "color": {"r": 255, "g": 255, "b": 255}, "color_mode": "color_temp"},
                "capabilities": ["brightness", "color_temp", "color"],
            },
        ],
    },

    # =========================================================================
    # PHILIPS HUE
    # =========================================================================
    "philips_hue": {
        "system_info": {
            "version": "1.65.0",
            "name": "Philips Hue Bridge",
            "model": "BSB002",
            "bridge_id": "001788FFFE2A5E3B",
            "device_count": 9,
            "group_count": 4,
            "scene_count": 6,
        },
        "devices": [
            {
                "name": "Hue White Ambiance вітальня",
                "type": "light",
                "room": "Living Room",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LWA004",
                "source_entity_id": "hue_light_1",
                "protocol_config": {"model_id": "LWA004"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 366},
                "capabilities": ["brightness", "color_temp"],
            },
            {
                "name": "Hue Color E27 вітальня",
                "type": "light",
                "room": "Living Room",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LCA001",
                "source_entity_id": "hue_light_2",
                "protocol_config": {"model_id": "LCA001"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 300, "color": {"r": 255, "g": 180, "b": 100}, "color_mode": "color_temp"},
                "capabilities": ["brightness", "color_temp", "color"],
            },
            {
                "name": "Hue Lightstrip Plus",
                "type": "light",
                "room": "Living Room",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LST002",
                "source_entity_id": "hue_light_3",
                "protocol_config": {"model_id": "LST002"},
                "state": {"state": "OFF", "brightness": 200, "color_temp": 300, "color": {"r": 255, "g": 0, "b": 128}, "color_mode": "color"},
                "capabilities": ["brightness", "color_temp", "color"],
            },
            {
                "name": "Hue White спальня",
                "type": "light",
                "room": "Bedroom",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LWB010",
                "source_entity_id": "hue_light_4",
                "protocol_config": {"model_id": "LWB010"},
                "state": {"state": "OFF", "brightness": 254},
                "capabilities": ["brightness"],
            },
            {
                "name": "Hue Go",
                "type": "light",
                "room": "Bedroom",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LLC020",
                "source_entity_id": "hue_light_5",
                "protocol_config": {"model_id": "LLC020"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 300, "color": {"r": 255, "g": 200, "b": 150}, "color_mode": "color_temp"},
                "capabilities": ["brightness", "color_temp", "color"],
            },
            {
                "name": "Hue GU10 кухня 1",
                "type": "light",
                "room": "Kitchen",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LCT024",
                "source_entity_id": "hue_light_6",
                "protocol_config": {"model_id": "LCT024"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 250},
                "capabilities": ["brightness", "color_temp"],
            },
            {
                "name": "Hue GU10 кухня 2",
                "type": "light",
                "room": "Kitchen",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LCT024",
                "source_entity_id": "hue_light_7",
                "protocol_config": {"model_id": "LCT024"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 250},
                "capabilities": ["brightness", "color_temp"],
            },
            {
                "name": "Hue Play Bar 1",
                "type": "light",
                "room": "Living Room",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LCT024",
                "source_entity_id": "hue_light_8",
                "protocol_config": {"model_id": "LCT024"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 300, "color": {"r": 0, "g": 100, "b": 255}, "color_mode": "color"},
                "capabilities": ["brightness", "color_temp", "color"],
            },
            {
                "name": "Hue Play Bar 2",
                "type": "light",
                "room": "Living Room",
                "protocol": "http_hue",
                "manufacturer": "Signify",
                "model": "LCT024",
                "source_entity_id": "hue_light_9",
                "protocol_config": {"model_id": "LCT024"},
                "state": {"state": "OFF", "brightness": 254, "color_temp": 300, "color": {"r": 255, "g": 50, "b": 0}, "color_mode": "color"},
                "capabilities": ["brightness", "color_temp", "color"],
            },
        ],
    },

    # =========================================================================
    # IKEA TRADFRI
    # =========================================================================
    "ikea_tradfri": {
        "system_info": {
            "version": "1.19.32",
            "name": "IKEA TRÅDFRI Gateway",
            "model": "E1526",
            "device_count": 7,
        },
        "devices": [
            {"name": "TRADFRI E27 вітальня", "type": "light", "room": "Вітальня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "LED1545G12", "source_entity_id": "tradfri_65537",
             "protocol_config": {"friendly_name": "tradfri_living_e27"}, "state": {"state": "OFF", "brightness": 254, "color_temp": 400}, "capabilities": ["brightness", "color_temp"]},
            {"name": "TRADFRI GU10 кухня", "type": "light", "room": "Кухня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "LED1650R5", "source_entity_id": "tradfri_65538",
             "protocol_config": {"friendly_name": "tradfri_kitchen_gu10"}, "state": {"state": "OFF", "brightness": 254, "color_temp": 370}, "capabilities": ["brightness", "color_temp"]},
            {"name": "TRADFRI E14 спальня", "type": "light", "room": "Спальня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "LED1649C5", "source_entity_id": "tradfri_65539",
             "protocol_config": {"friendly_name": "tradfri_bedroom_e14"}, "state": {"state": "OFF", "brightness": 200}, "capabilities": ["brightness"]},
            {"name": "FYRTUR рулонна штора", "type": "cover", "room": "Спальня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "E1757", "source_entity_id": "tradfri_65540",
             "protocol_config": {"friendly_name": "fyrtur_bedroom"}, "state": {"state": "closed", "position": 0, "tilt_position": 0}, "capabilities": ["position"]},
            {"name": "KADRILJ рулонна штора", "type": "cover", "room": "Вітальня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "E1926", "source_entity_id": "tradfri_65541",
             "protocol_config": {"friendly_name": "kadrilj_living"}, "state": {"state": "closed", "position": 0, "tilt_position": 0}, "capabilities": ["position"]},
            {"name": "TRADFRI розетка", "type": "switch", "room": "Кухня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "E1603", "source_entity_id": "tradfri_65542",
             "protocol_config": {"friendly_name": "tradfri_kitchen_plug"}, "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": ["power_monitoring"]},
            {"name": "TRADFRI LED стрічка", "type": "light", "room": "Кухня", "protocol": "zigbee2mqtt", "manufacturer": "IKEA", "model": "LED1733G7", "source_entity_id": "tradfri_65543",
             "protocol_config": {"friendly_name": "tradfri_kitchen_strip"}, "state": {"state": "OFF", "brightness": 254, "color_temp": 300, "color": {"r": 255, "g": 255, "b": 255}, "color_mode": "color_temp"}, "capabilities": ["brightness", "color_temp", "color"]},
        ],
    },

    # =========================================================================
    # MQTT BROKER
    # =========================================================================
    "mqtt_broker": {
        "system_info": {
            "version": "2.0.21",
            "name": "Eclipse Mosquitto",
            "device_count": 6,
            "topic_count": 24,
        },
        "devices": [
            {"name": "Tasmota розетка кухня", "type": "switch", "room": "Кухня", "protocol": "mqtt", "manufacturer": "BlitzWolf", "model": "BW-SHP13", "source_entity_id": "tasmota_kitchen",
             "protocol_config": {"topic_scheme": "tasmota", "device_name": "tasmota_kitchen", "friendly_name": "tasmota_kitchen"}, "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": ["power_monitoring"]},
            {"name": "Shelly 1PM коридор", "type": "switch", "room": "Коридор", "protocol": "mqtt", "manufacturer": "Shelly", "model": "Shelly 1PM", "source_entity_id": "shelly_hallway",
             "protocol_config": {"topic_scheme": "shelly", "device_name": "shelly_hallway", "friendly_name": "shelly_hallway"}, "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": ["power_monitoring"]},
            {"name": "Shelly H&T ванна", "type": "sensor", "room": "Ванна", "protocol": "mqtt", "manufacturer": "Shelly", "model": "Shelly H&T", "source_entity_id": "shelly_ht_bath",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "shellies/shelly_ht_bath/sensor", "device_name": "shelly_ht_bath", "friendly_name": "shelly_ht_bath"}, "state": {"temperature": 23.5, "humidity": 68, "battery": 100}, "capabilities": ["temperature", "humidity", "battery"]},
            {"name": "Sonoff Basic гараж", "type": "switch", "room": "Гараж", "protocol": "mqtt", "manufacturer": "Sonoff", "model": "Basic R2", "source_entity_id": "sonoff_garage",
             "protocol_config": {"topic_scheme": "tasmota", "device_name": "sonoff_garage", "friendly_name": "sonoff_garage"}, "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": []},
            {"name": "WiFi термометр балкон", "type": "sensor", "room": "Балкон", "protocol": "mqtt", "manufacturer": "ESP32", "model": "DIY Sensor", "source_entity_id": "esp32_balcony",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "sensors/balcony", "device_name": "esp32_balcony", "friendly_name": "esp32_balcony"}, "state": {"temperature": 8.5, "humidity": 75, "battery": 100}, "capabilities": ["temperature", "humidity"]},
            {"name": "Tasmota лампа кабінет", "type": "light", "room": "Кабінет", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi Bulb E27", "source_entity_id": "tasmota_office_bulb",
             "protocol_config": {"topic_scheme": "tasmota", "device_name": "tasmota_office", "friendly_name": "tasmota_office"}, "state": {"state": "OFF", "brightness": 254, "color_temp": 300}, "capabilities": ["brightness", "color_temp"]},
        ],
    },

    # =========================================================================
    # TUYA / SMARTLIFE
    # =========================================================================
    "tuya": {
        "system_info": {
            "version": "2.0",
            "name": "Tuya Cloud IoT Core",
            "region": "EU",
            "uid": "eu1642857***",
            "device_count": 9,
        },
        "devices": [
            {"name": "WiFi лампа вітальня", "type": "light", "room": "Вітальня", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi RGBCW Bulb", "source_entity_id": "tuya_bfa3821c",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/bfa3821c", "device_name": "tuya_bulb_living", "friendly_name": "tuya_bulb_living", "dp_codes": {"1": "switch_led", "2": "bright_value_v2", "3": "temp_value_v2", "5": "colour_data_v2"}},
             "state": {"state": "OFF", "brightness": 254, "color_temp": 300, "color": {"r": 255, "g": 255, "b": 255}, "color_mode": "color_temp"}, "capabilities": ["brightness", "color_temp", "color"]},
            {"name": "Розумна розетка", "type": "switch", "room": "Кухня", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi Smart Plug", "source_entity_id": "tuya_c4e291ba",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/c4e291ba", "device_name": "tuya_plug_kitchen", "friendly_name": "tuya_plug_kitchen", "dp_codes": {"1": "switch_1", "9": "cur_current", "18": "cur_power", "19": "cur_voltage"}},
             "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": ["power_monitoring"]},
            {"name": "Мотор для штор", "type": "cover", "room": "Спальня", "protocol": "mqtt", "manufacturer": "Zemismart", "model": "WiFi Curtain Motor", "source_entity_id": "tuya_d5f8e231",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/d5f8e231", "device_name": "tuya_curtain_bed", "friendly_name": "tuya_curtain_bed", "dp_codes": {"1": "control", "2": "percent_control", "3": "percent_state"}},
             "state": {"state": "closed", "position": 0, "tilt_position": 0}, "capabilities": ["position"]},
            {"name": "ІЧ пульт керування", "type": "switch", "room": "Вітальня", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi IR Remote", "source_entity_id": "tuya_a9b3c721",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/a9b3c721", "device_name": "tuya_ir_living", "friendly_name": "tuya_ir_living"},
             "state": {"state": "OFF"}, "capabilities": []},
            {"name": "Датчик температури/вологості", "type": "sensor", "room": "Спальня", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi T&H Sensor", "source_entity_id": "tuya_e7d4f892",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/e7d4f892", "device_name": "tuya_th_bedroom", "friendly_name": "tuya_th_bedroom", "dp_codes": {"1": "temp_current", "2": "humidity_value"}},
             "state": {"temperature": 21.3, "humidity": 55, "battery": 82}, "capabilities": ["temperature", "humidity", "battery"]},
            {"name": "Датчик дверей", "type": "sensor", "room": "Коридор", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi Door Sensor", "source_entity_id": "tuya_f1a2b3c4",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/f1a2b3c4", "device_name": "tuya_door_hall", "friendly_name": "tuya_door_hall", "dp_codes": {"1": "doorcontact_state"}},
             "state": {"contact": True, "battery": 90}, "capabilities": ["contact", "battery"]},
            {"name": "Розумна лампа спальня", "type": "light", "room": "Спальня", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi Dimmer Bulb", "source_entity_id": "tuya_b2c3d4e5",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/b2c3d4e5", "device_name": "tuya_bulb_bed", "friendly_name": "tuya_bulb_bed"},
             "state": {"state": "OFF", "brightness": 254, "color_temp": 370}, "capabilities": ["brightness", "color_temp"]},
            {"name": "Подвійна розетка", "type": "switch", "room": "Кабінет", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi Dual Plug", "source_entity_id": "tuya_g5h6i7j8",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/g5h6i7j8", "device_name": "tuya_plug_office", "friendly_name": "tuya_plug_office"},
             "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": ["power_monitoring"]},
            {"name": "Датчик руху", "type": "sensor", "room": "Коридор", "protocol": "mqtt", "manufacturer": "Tuya", "model": "WiFi PIR Sensor", "source_entity_id": "tuya_k9l0m1n2",
             "protocol_config": {"topic_scheme": "generic", "base_topic": "tuya/k9l0m1n2", "device_name": "tuya_pir_hall", "friendly_name": "tuya_pir_hall"},
             "state": {"occupancy": False, "battery": 76, "illuminance": 30}, "capabilities": ["occupancy", "battery", "illuminance"]},
        ],
    },

    # =========================================================================
    # SAMSUNG SMARTTHINGS
    # =========================================================================
    "smartthings": {
        "system_info": {
            "version": "API v1",
            "name": "Samsung SmartThings",
            "location": "Home",
            "device_count": 7,
        },
        "devices": [
            {"name": "Samsung TV", "type": "media_player", "room": "Вітальня", "protocol": "http", "manufacturer": "Samsung", "model": "QE55Q80B", "source_entity_id": "st_tv_001",
             "protocol_config": {"friendly_name": "samsung_tv", "manufacturer": "Samsung", "model_id": "QE55Q80B"},
             "state": {"state": "idle", "volume_level": 0.25, "is_volume_muted": False, "media_title": "", "media_artist": "", "media_content_type": "video", "source": "HDMI1"}, "capabilities": ["volume", "media_control", "source"]},
            {"name": "SmartThings Motion Sensor", "type": "sensor", "room": "Коридор", "protocol": "http", "manufacturer": "Samsung", "model": "GP-U999SJVLGDA", "source_entity_id": "st_motion_001",
             "protocol_config": {"friendly_name": "st_motion_hall", "manufacturer": "Samsung", "model_id": "GP-U999SJVLGDA"},
             "state": {"occupancy": False, "battery": 88, "illuminance": 120}, "capabilities": ["occupancy", "battery", "illuminance"]},
            {"name": "SmartThings Multipurpose", "type": "sensor", "room": "Коридор", "protocol": "http", "manufacturer": "Samsung", "model": "GP-U999SJVLAEA", "source_entity_id": "st_multi_001",
             "protocol_config": {"friendly_name": "st_multi_door", "manufacturer": "Samsung", "model_id": "GP-U999SJVLAEA"},
             "state": {"contact": True, "battery": 91, "temperature": 22.1}, "capabilities": ["contact", "battery"]},
            {"name": "SmartThings Outlet", "type": "switch", "room": "Кабінет", "protocol": "http", "manufacturer": "Samsung", "model": "GP-U999SJVLDAA", "source_entity_id": "st_outlet_001",
             "protocol_config": {"friendly_name": "st_outlet_office", "manufacturer": "Samsung", "model_id": "GP-U999SJVLDAA"},
             "state": {"state": "OFF", "power_consumption": 0.0, "voltage": 230.0, "current": 0.0}, "capabilities": ["power_monitoring"]},
            {"name": "SmartThings лампа", "type": "light", "room": "Спальня", "protocol": "http", "manufacturer": "Samsung", "model": "GP-LBU019BBAWU", "source_entity_id": "st_light_001",
             "protocol_config": {"friendly_name": "st_light_bedroom", "manufacturer": "Samsung", "model_id": "GP-LBU019BBAWU"},
             "state": {"state": "OFF", "brightness": 254, "color_temp": 350}, "capabilities": ["brightness", "color_temp"]},
            {"name": "SmartThings Button", "type": "sensor", "room": "Спальня", "protocol": "http", "manufacturer": "Samsung", "model": "GP-U999SJVLEAA", "source_entity_id": "st_button_001",
             "protocol_config": {"friendly_name": "st_button_bed", "manufacturer": "Samsung", "model_id": "GP-U999SJVLEAA"},
             "state": {"battery": 95}, "capabilities": ["battery"]},
            {"name": "Samsung кондиціонер", "type": "climate", "room": "Вітальня", "protocol": "http", "manufacturer": "Samsung", "model": "AR12TXHQASINUA", "source_entity_id": "st_ac_001",
             "protocol_config": {"friendly_name": "samsung_ac", "manufacturer": "Samsung", "model_id": "AR12TXHQASINUA"},
             "state": {"current_temperature": 24.0, "target_temperature": 23.0, "hvac_mode": "cool", "fan_mode": "auto", "preset": "none", "humidity": 55}, "capabilities": ["temperature", "humidity", "fan_mode"]},
        ],
    },
}
